<?php

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_58a49542118e4',
	'title' => 'Flexible Content',
	'fields' => array(
		array(
			'key' => 'field_58a495421bd28',
			'label' => 'Content',
			'name' => 'content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'568d6dc0c70f2' => array(
					'key' => '568d6dc0c70f2',
					'name' => 'one-column',
					'label' => 'One Column',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_58efb7ddb40f5',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b6e111e235b0',
							'label' => 'Section Settings',
							'name' => 'style',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 1,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5b6e1130235b1',
									'label' => 'Background',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6e113c235b2',
									'label' => 'Background',
									'name' => 'background',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'bg-none' => 'None',
										'bg-color' => 'Color',
										'bg-image' => 'Image',
										'bg-video' => 'Video',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'bg-none',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b6e11cb235b3',
									'label' => 'Background Color',
									'name' => 'background_color',
									'type' => 'color_picker',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-color',
											),
										),
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-image',
											),
										),
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-video',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '#FFFFFF',
								),
								array(
									'key' => 'field_5b6e11fb235b4',
									'label' => 'Background Video',
									'name' => 'background_video',
									'type' => 'text',
									'instructions' => 'Insert a Youtube link',
									'required' => 1,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-video',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b6e121f235b5',
									'label' => '',
									'name' => '',
									'type' => 'message',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-video',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => 'In addition to the video, you must upload an image to use as fallback while the video loads or in the case that the video doesn\'t load or the page is being viewed on mobile.',
									'new_lines' => 'wpautop',
									'esc_html' => 0,
								),
								array(
									'key' => 'field_5b6e123f235b6',
									'label' => 'Background Image',
									'name' => 'background_image',
									'type' => 'image',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-image',
											),
										),
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-video',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'url',
									'preview_size' => 'medium',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5b9711658192d',
									'label' => 'Overlay',
									'name' => 'overlay',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-image',
											),
										),
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '==',
												'value' => 'bg-video',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 1,
									'max' => 1,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'field_5b9711768192e',
											'label' => 'Color',
											'name' => 'color',
											'type' => 'color_picker',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
										),
										array(
											'key' => 'field_5b97117c8192f',
											'label' => 'Opacity',
											'name' => 'opacity',
											'type' => 'number',
											'instructions' => '0-1 (eg. 0 for no opacity, 0.5 for half opacity, 1 for full opacity)',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'min' => 0,
											'max' => 1,
											'step' => '0.01',
										),
									),
								),
								array(
									'key' => 'field_5b6e127c235b8',
									'label' => 'White Text',
									'name' => 'white_text',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6e113c235b2',
												'operator' => '!=',
												'value' => 'bg-none',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5b7effba7bec1',
									'label' => 'Width',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6e12ac235ba',
									'label' => 'Width',
									'name' => 'width',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'narrow' => 'Narrow',
										'normal' => 'Normal',
										'wide' => 'Wide',
										'full-width' => 'Full-width',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'normal',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b7effc17bec2',
									'label' => 'Height',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6e12e4235bb',
									'label' => 'Height',
									'name' => 'height',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'auto' => 'Auto',
										'min' => 'Min height (300px)',
										'full' => 'Full height',
										'custom' => 'Custom',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b7f001cf0c0a',
									'label' => 'Custom Height',
									'name' => 'height_custom',
									'type' => 'text',
									'instructions' => 'This will be the minimum height. Eg. 500px or 50vh (50% of screen height)',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6e12e4235bb',
												'operator' => '==',
												'value' => 'custom',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b7f0037f0c0b',
									'label' => 'Alignment',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b7f003ff0c0c',
									'label' => 'Content Alignment',
									'name' => 'content_alignment',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'top' => 'Top',
										'middle' => 'Middle',
										'bottom' => 'Bottom',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b6e12a3235b9',
									'label' => 'Padding',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6e1305235bc',
									'label' => 'Padding',
									'name' => 'padding',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 1,
									'max' => 1,
									'layout' => 'table',
									'button_label' => '',
									'sub_fields' => array(
										array(
											'key' => 'field_5b6e132d235bd',
											'label' => 'Top',
											'name' => 'top',
											'type' => 'radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'Small' => 'Small',
												'Normal' => 'Normal',
												'None' => 'None',
											),
											'allow_null' => 0,
											'other_choice' => 0,
											'default_value' => 'Normal',
											'layout' => 'horizontal',
											'return_format' => 'value',
											'save_other_choice' => 0,
										),
										array(
											'key' => 'field_5b6e133c235be',
											'label' => 'Bottom',
											'name' => 'bottom',
											'type' => 'radio',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'Small' => 'Small',
												'Normal' => 'Normal',
												'None' => 'None',
											),
											'allow_null' => 0,
											'other_choice' => 0,
											'default_value' => 'Normal',
											'layout' => 'horizontal',
											'return_format' => 'value',
											'save_other_choice' => 0,
										),
									),
								),
								array(
									'key' => 'field_5b6e1362235bf',
									'label' => 'Border',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6e136d235c0',
									'label' => 'Border',
									'name' => 'border',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'border-top' => 'Top (section width)',
										'border-bottom' => 'Bottom (section width)',
										'border-top-content' => 'Top (content width)',
										'border-bottom-content' => 'Bottom (content width)',
									),
									'allow_custom' => 0,
									'default_value' => array(
									),
									'layout' => 'vertical',
									'toggle' => 0,
									'return_format' => 'value',
									'save_custom' => 0,
								),
								array(
									'key' => 'field_5b6e139a235c1',
									'label' => 'Anchor Link',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6e13a5235c2',
									'label' => 'Section ID',
									'name' => 'section_id',
									'type' => 'text',
									'instructions' => 'Give this section a unique ID to use for anchor linking. For example, a section with a unique ID "my-section" can be anchor linked to via #my-section or yoursite.com/your-url/#my-section',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),
						array(
							'key' => 'field_59ee282990549',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_58a495421e0ad',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => 'XXXXXXKIMXXXXXX',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
						),
						array(
							'key' => 'field_59ee282090548',
							'label' => 'Header',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_59ee27f790546',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
						),
						array(
							'key' => 'field_59ee28329054a',
							'label' => 'Footer',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_59ee280c90547',
							'label' => 'Footer',
							'name' => 'footer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5693e9f28ca21' => array(
					'key' => '5693e9f28ca21',
					'name' => 'two-columns',
					'label' => 'Two Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_58eff848a4023_field_58efb7ddb40f5',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'_clone' => 'field_58eff848a4023',
							'__key' => 'field_58efb7ddb40f5',
							'__name' => 'layout_title',
							'__label' => 'Layout Title',
						),
						array(
							'key' => 'field_5b73009008116',
							'label' => 'Section Settings',
							'name' => 'style',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b6e111e235b0',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_59dfd99ee3af9',
							'label' => 'Column Settings',
							'name' => 'column_settings',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 1,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5b5a5e8ec9f23',
									'label' => 'Width',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_59dfd9ace3afa',
									'label' => 'Column Widths',
									'name' => 'column_width',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => 'rb-2-col-opts',
										'id' => '',
									),
									'choices' => array(
										'1_1' => '1_1',
										'1_3' => '1_3',
										'3_1' => '3_1',
										'5_7' => '5_7',
										'7_5' => '7_5',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5b6c8b3e2416f',
									'label' => 'Height',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6c8b5a24170',
									'label' => 'Height',
									'name' => 'column_height',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'auto' => 'Auto',
										'min' => 'Min height (300px)',
										'full' => 'Full height',
										'custom' => 'Custom',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5b6c8bf424171',
									'label' => 'Custom Height',
									'name' => 'column_custom_height',
									'type' => 'text',
									'instructions' => 'This will be the minimum height. Eg. 500px or 50vh (50% of screen height)',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b6c8b5a24170',
												'operator' => '==',
												'value' => 'custom',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b6c8c1924172',
									'label' => 'Alignment',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6c8c2824173',
									'label' => 'Text Alignment',
									'name' => 'column_text_alignment',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'top' => 'Top',
										'middle' => 'Middle',
										'bottom' => 'Bottom',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5b6c8c5d24174',
									'label' => 'Spacing',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6c8c6b24175',
									'label' => 'Gutter',
									'name' => 'gutter',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'none' => 'None',
										'normal' => 'Normal',
										'double' => 'Double',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => 'normal',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b6c8c9124176',
									'label' => 'Style',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b6c8ca024177',
									'label' => 'Styles',
									'name' => 'styles',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'box' => 'Box',
										'border' => 'Border',
									),
									'allow_custom' => 0,
									'default_value' => array(
									),
									'layout' => 'horizontal',
									'toggle' => 0,
									'return_format' => 'value',
									'save_custom' => 0,
								),
								array(
									'key' => 'field_5b5bad0a9b38b',
									'label' => 'Mobile',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b5bad179b38c',
									'label' => 'Reverse Stacking',
									'name' => 'reverse_stacking',
									'type' => 'true_false',
									'instructions' => 'Stack the the right column first on mobile.',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5b90636da6001',
									'label' => 'Show background image of empty columns',
									'name' => 'show_background_image_of_empty_columns',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5b9065fff017b',
									'label' => 'Border',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b906626f017c',
									'label' => 'Border',
									'name' => 'column_border',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'border-col-side' => 'Side',
										'border-col-top' => 'Top',
										'border-col-bottom' => 'Bottom',
									),
									'allow_custom' => 0,
									'default_value' => array(
									),
									'layout' => 'horizontal',
									'toggle' => 0,
									'return_format' => 'value',
									'save_custom' => 0,
								),
							),
						),
						array(
							'key' => 'field_59ee28547bc9c',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_58a495421e0ee',
							'label' => 'Column Content',
							'name' => 'column_content',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 2,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Column',
							'sub_fields' => array(
								array(
									'key' => 'field_5b73425deeef9',
									'label' => 'Column Settings',
									'name' => 'column_settings',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5b6e1130235b1',
										1 => 'field_5b6e113c235b2',
										2 => 'field_5b6e11cb235b3',
										3 => 'field_5b6e11fb235b4',
										4 => 'field_5b6e121f235b5',
										5 => 'field_5b6e123f235b6',
										6 => 'field_5b9711658192d',
										7 => 'field_5b6e127c235b8',
									),
									'display' => 'group',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
								array(
									'key' => 'field_58a4954236e19',
									'label' => 'Column',
									'name' => 'column',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 1,
								),
							),
						),
						array(
							'key' => 'field_59ee285f7bc9d',
							'label' => 'Header',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_59ee28677bc9e_field_59ee27f790546',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_59ee28677bc9e',
							'__key' => 'field_59ee27f790546',
							'__name' => 'header',
							'__label' => 'Header',
						),
						array(
							'key' => 'field_59ee28767bc9f',
							'label' => 'Footer',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_59ee2889ef1c1_field_59ee280c90547',
							'label' => 'Footer',
							'name' => 'footer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_59ee2889ef1c1',
							'__key' => 'field_59ee280c90547',
							'__name' => 'footer',
							'__label' => 'Footer',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5a0b6094a558b' => array(
					'key' => '5a0b6094a558b',
					'name' => 'multi-columns',
					'label' => 'Multi Columns',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5a0b6094a558c_field_58efb7ddb40f5',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'_clone' => 'field_5a0b6094a558c',
							'__key' => 'field_58efb7ddb40f5',
							'__name' => 'layout_title',
							'__label' => 'Layout Title',
						),
						array(
							'key' => 'field_5b7300c4b2413',
							'label' => 'Section Settings',
							'name' => 'style',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b6e111e235b0',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5a0b6094a558e',
							'label' => 'Column Settings',
							'name' => 'column_settings',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 1,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5a0b612fa129e',
									'label' => 'Columns',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5a0b613aa129f',
									'label' => 'Columns per row',
									'name' => 'columns_per_row',
									'type' => 'radio',
									'instructions' => 'Choose the number of columns to show per row then click "Add Column" to add more columns',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										3 => '3',
										4 => '4',
										5 => '5',
										6 => '6',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5b7342c60643e',
									'label' => 'Clone from 2col Column Settings',
									'name' => 'clone_from_2col_column_settings',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5b6c8b3e2416f',
										1 => 'field_5b6c8b5a24170',
										2 => 'field_5b6c8bf424171',
										3 => 'field_5b6c8c1924172',
										4 => 'field_5b6c8c2824173',
										5 => 'field_5b6c8c5d24174',
										6 => 'field_5b6c8c6b24175',
										7 => 'field_5b6c8c9124176',
										8 => 'field_5b6c8ca024177',
										9 => 'field_5b5bad0a9b38b',
										10 => 'field_5b90636da6001',
										11 => 'field_5b9065fff017b',
										12 => 'field_5b906626f017c',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
							),
						),
						array(
							'key' => 'field_5a0b6094a5593',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5a0b6094a5594',
							'label' => 'Column Content',
							'name' => 'column_content',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 3,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Column',
							'sub_fields' => array(
								array(
									'key' => 'field_5b6c8ef3c7340_field_5b6c8d53c42bc',
									'label' => 'Column Settings',
									'name' => 'column_settings',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5b73425deeef9',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
								array(
									'key' => 'field_5a0b6094a5595',
									'label' => 'Column',
									'name' => 'column',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 1,
								),
							),
						),
						array(
							'key' => 'field_5a0b6094a5596',
							'label' => 'Header',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5a0b6094a5597_field_59ee27f790546',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5a0b6094a5597',
							'__key' => 'field_59ee27f790546',
							'__name' => 'header',
							'__label' => 'Header',
						),
						array(
							'key' => 'field_5a0b6094a5598',
							'label' => 'Footer',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5a0b6094a5599_field_59ee280c90547',
							'label' => 'Footer',
							'name' => 'footer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5a0b6094a5599',
							'__key' => 'field_59ee280c90547',
							'__name' => 'footer',
							'__label' => 'Footer',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b5f79fc0d2fc' => array(
					'key' => '5b5f79fc0d2fc',
					'name' => 'image_text',
					'label' => 'Image + Text',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5f79fc0d2fd_field_58efb7ddb40f5',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'_clone' => 'field_5b5f79fc0d2fd',
							'__key' => 'field_58efb7ddb40f5',
							'__name' => 'layout_title',
							'__label' => 'Layout Title',
						),
						array(
							'key' => 'field_5b7300dab2414',
							'label' => 'Section Settings',
							'name' => 'style',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b6e111e235b0',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5b5f79fd0d2ff',
							'label' => 'Column Settings',
							'name' => 'column_settings',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 1,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5b7343aa0643f',
									'label' => 'Clone from 2col Column Settings',
									'name' => 'clone_from_2col_column_settings',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5b6c8b3e2416f',
										1 => 'field_5b6c8b5a24170',
										2 => 'field_5b6c8bf424171',
										3 => 'field_5b6c8c1924172',
										4 => 'field_5b6c8c2824173',
										5 => 'field_5b6c8c5d24174',
										6 => 'field_5b6c8c6b24175',
										7 => 'field_5b6c8c9124176',
										8 => 'field_5b6c8ca024177',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
							),
						),
						array(
							'key' => 'field_5b5f79fd0d303',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f79fd0d304',
							'label' => 'Column Content',
							'name' => 'column_content',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 2,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Column',
							'sub_fields' => array(
								array(
									'key' => 'field_5b5f79fd0d305_field_5b5a31ca19fba',
									'label' => 'Column Settings',
									'name' => 'column_settings',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5b73425deeef9',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
								array(
									'key' => 'field_5b5f7a480d30b',
									'label' => 'Image',
									'name' => 'image',
									'type' => 'image',
									'instructions' => '',
									'required' => 1,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'return_format' => 'array',
									'preview_size' => 'thumbnail',
									'library' => 'all',
									'min_width' => '',
									'min_height' => '',
									'min_size' => '',
									'max_width' => '',
									'max_height' => '',
									'max_size' => '',
									'mime_types' => '',
								),
								array(
									'key' => 'field_5b5f79fd0d306',
									'label' => 'Column',
									'name' => 'column',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 1,
								),
							),
						),
						array(
							'key' => 'field_5b5f79fd0d307',
							'label' => 'Header',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f79fd0d308_field_59ee27f790546',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5b5f79fd0d308',
							'__key' => 'field_59ee27f790546',
							'__name' => 'header',
							'__label' => 'Header',
						),
						array(
							'key' => 'field_5b5f79fd0d309',
							'label' => 'Footer',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f79fd0d30a_field_59ee280c90547',
							'label' => 'Footer',
							'name' => 'footer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5b5f79fd0d30a',
							'__key' => 'field_59ee280c90547',
							'__name' => 'footer',
							'__label' => 'Footer',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b5f42fca40e5' => array(
					'key' => '5b5f42fca40e5',
					'name' => 'carousel',
					'label' => 'Carousel',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5f42fca40e6_field_58efb7ddb40f5',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'_clone' => 'field_5b5f42fca40e6',
							'__key' => 'field_58efb7ddb40f5',
							'__name' => 'layout_title',
							'__label' => 'Layout Title',
						),
						array(
							'key' => 'field_5b7300f9b2415',
							'label' => 'Section Settings',
							'name' => 'style',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b6e111e235b0',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5b5f42fca40e8',
							'label' => 'Carousel Settings',
							'name' => 'column_settings',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 1,
							'layout' => 'block',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5b5f42fca40e9',
									'label' => 'Slides',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b5f42fca40ea',
									'label' => 'Slides per row',
									'name' => 'columns_per_row',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										1 => '1',
										2 => '2',
										3 => '3',
										4 => '4',
										5 => '5',
										6 => '6',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
									'save_other_choice' => 0,
								),
								array(
									'key' => 'field_5b984263229c2',
									'label' => 'Alignment',
									'name' => 'alignment',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5b6c8c2824173',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
								array(
									'key' => 'field_5b5f4b9f4b6b5',
									'label' => 'UI',
									'name' => '',
									'type' => 'tab',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'placement' => 'top',
									'endpoint' => 0,
								),
								array(
									'key' => 'field_5b5f4bad4b6b6',
									'label' => 'Navigation',
									'name' => 'navigation',
									'type' => 'checkbox',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'dots' => 'Dots',
										'arrows' => 'Arrows',
									),
									'allow_custom' => 0,
									'save_custom' => 0,
									'default_value' => array(
										0 => 'dots',
										1 => 'arrows',
									),
									'layout' => 'horizontal',
									'toggle' => 0,
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5b5f4cdfd0e2f',
									'label' => 'Effect',
									'name' => 'effect',
									'type' => 'radio',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'choices' => array(
										'slide' => 'Slide',
										'fade' => 'Fade',
									),
									'allow_null' => 0,
									'other_choice' => 0,
									'save_other_choice' => 0,
									'default_value' => '',
									'layout' => 'horizontal',
									'return_format' => 'value',
								),
								array(
									'key' => 'field_5b5f4d0cd0e30',
									'label' => 'Autoplay',
									'name' => 'autoplay',
									'type' => 'true_false',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'message' => '',
									'default_value' => 0,
									'ui' => 0,
									'ui_on_text' => '',
									'ui_off_text' => '',
								),
								array(
									'key' => 'field_5b5f61333fa14',
									'label' => 'Speed',
									'name' => 'speed',
									'type' => 'range',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => array(
										array(
											array(
												'field' => 'field_5b5f4d0cd0e30',
												'operator' => '==',
												'value' => '1',
											),
										),
									),
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => 3,
									'min' => 1,
									'max' => 10,
									'step' => 1,
									'prepend' => '',
									'append' => 'seconds',
								),
							),
						),
						array(
							'key' => 'field_5b5f42fca40ec',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f42fca40ed',
							'label' => 'Column Content',
							'name' => 'column_content',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Carousel Item',
							'sub_fields' => array(
								array(
									'key' => 'field_5b73441506440',
									'label' => 'Column Settings',
									'name' => 'column_settings',
									'type' => 'clone',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'clone' => array(
										0 => 'field_5b73425deeef9',
									),
									'display' => 'seamless',
									'layout' => 'block',
									'prefix_label' => 0,
									'prefix_name' => 0,
								),
								array(
									'key' => 'field_5b5f42fca40ef',
									'label' => 'Column',
									'name' => 'column',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 1,
								),
							),
						),
						array(
							'key' => 'field_5b5f42fca40f0',
							'label' => 'Header',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f42fca40f1_field_59ee27f790546',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5b5f42fca40f1',
							'__key' => 'field_59ee27f790546',
							'__name' => 'header',
							'__label' => 'Header',
						),
						array(
							'key' => 'field_5b5f42fca40f2',
							'label' => 'Footer',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f42fca40f3_field_59ee280c90547',
							'label' => 'Footer',
							'name' => 'footer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5b5f42fca40f3',
							'__key' => 'field_59ee280c90547',
							'__name' => 'footer',
							'__label' => 'Footer',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b5f7e292f709' => array(
					'key' => '5b5f7e292f709',
					'name' => 'accordion',
					'label' => 'Accordion',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_5b5f7e292f70a_field_58efb7ddb40f5',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'_clone' => 'field_5b5f7e292f70a',
							'__key' => 'field_58efb7ddb40f5',
							'__name' => 'layout_title',
							'__label' => 'Layout Title',
						),
						array(
							'key' => 'field_5b73010bb2416',
							'label' => 'Section Settings',
							'name' => 'style',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'field_5b6e111e235b0',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5b5f7e292f715',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f7e292f716',
							'label' => 'Content',
							'name' => 'accordion_item',
							'type' => 'repeater',
							'instructions' => 'If organizing the accordion items into categories, put the category name into the \'Category\' field and use the \'Add Category\' button to add more categories and category items. Otherwise, leave the first \'Category\' field blank and use only the \'Add Item\' button.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 0,
							'layout' => 'block',
							'button_label' => 'Add Category',
							'sub_fields' => array(
								array(
									'key' => 'field_5b731e8bccf4e',
									'label' => 'Category',
									'name' => 'category',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5b730195ccf4d',
									'label' => 'Items',
									'name' => 'items',
									'type' => 'repeater',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'collapsed' => '',
									'min' => 1,
									'max' => 0,
									'layout' => 'block',
									'button_label' => 'Add Item',
									'sub_fields' => array(
										array(
											'key' => 'field_5b5f7ebc2f71d',
											'label' => 'Title',
											'name' => 'title',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
										array(
											'key' => 'field_5b5f7e292f718',
											'label' => 'Content',
											'name' => 'content',
											'type' => 'wysiwyg',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'tabs' => 'all',
											'toolbar' => 'full',
											'media_upload' => 1,
											'delay' => 1,
										),
									),
								),
							),
						),
						array(
							'key' => 'field_5b5f7e292f719',
							'label' => 'Header',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f7e292f71a_field_59ee27f790546',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5b5f7e292f71a',
							'__key' => 'field_59ee27f790546',
							'__name' => 'header',
							'__label' => 'Header',
						),
						array(
							'key' => 'field_5b5f7e292f71b',
							'label' => 'Footer',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5b5f7e292f71c_field_59ee280c90547',
							'label' => 'Footer',
							'name' => 'footer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => 'editor-short',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 1,
							'_clone' => 'field_5b5f7e292f71c',
							'__key' => 'field_59ee280c90547',
							'__name' => 'footer',
							'__label' => 'Footer',
						),
					),
					'min' => '',
					'max' => '',
				),
				'589a2aeeaa001' => array(
					'key' => '589a2aeeaa001',
					'name' => 'html',
					'label' => 'HTML',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_58eff91fa4027_field_58efb7ddb40f5',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'_clone' => 'field_58eff91fa4027',
							'__key' => 'field_58efb7ddb40f5',
							'__name' => 'layout_title',
							'__label' => 'Layout Title',
						),
						array(
							'key' => 'field_58a495421e2bd',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'new_lines' => '',
							'maxlength' => '',
							'placeholder' => '',
							'rows' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c1a96b8d5d5e' => array(
					'key' => 'layout_5c1a96b8d5d5e',
					'name' => 'popup',
					'label' => 'Popup',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c1a96b8d5d5f',
							'label' => 'Layout Title',
							'name' => 'layout_title',
							'type' => 'text',
							'instructions' => 'For editing use only.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c1a96ccd5d61',
							'label' => 'ID',
							'name' => 'id',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5c1a96f6d5d62',
							'label' => '',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '<p>Hook a link to this popup to trigger it by adding the following code into your link in Text mode (replace "your_id" with your popup ID):</p>

<code>data-toggle="modal" data-target="#your_id"</code>

<p>Your link should look like this:</p>

<code>&lt;a href="#" data-toggle="modal" data-target="#your_id"&gt;Button text goes here&lt;/a&gt;</code>',
							'new_lines' => '',
							'esc_html' => 0,
						),
						array(
							'key' => 'field_5c1a9b9dfbdc0',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5c1a96b8d5d60',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5c1a9bb5fbdc3',
							'label' => 'Header',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5c1a9ba8fbdc1',
							'label' => 'Header',
							'name' => 'header',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_5c1a9bbdfbdc4',
							'label' => 'Footer',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_5c1a9baffbdc2',
							'label' => 'Footer',
							'name' => 'footer',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5a1debe99b0c7' => array(
					'key' => '5a1debe99b0c7',
					'name' => 'reusable_block',
					'label' => 'Reusable Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5a1debf79b0c8',
							'label' => 'Choose Reusable Block',
							'name' => 'choose_reusable_block',
							'type' => 'post_object',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'post_type' => array(
								0 => 'reusable_block',
							),
							'taxonomy' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'return_format' => 'object',
							'ui' => 1,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5bdcb2c5f22ca' => array(
					'key' => 'layout_5bdcb2c5f22ca',
					'name' => 'anchor_menu',
					'label' => 'Anchor Menu',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bdcb2c8f22cb',
							'label' => '',
							'name' => '',
							'type' => 'message',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => 'Display the anchor menu',
							'new_lines' => 'wpautop',
							'esc_html' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Content Section',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
			array(
				'param' => 'page_type',
				'operator' => '!=',
				'value' => 'posts_page',
			),
			array(
				'param' => 'page_template',
				'operator' => '!=',
				'value' => 'styleguide.php',
			),
		),
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'reusable_block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;

?>